# Generated by Django 4.0 on 2021-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0003_rename_profile_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('charges', models.TextField()),
                ('description', models.TextField()),
                ('accuser', models.CharField(max_length=200)),
                ('accuseraddress', models.CharField(max_length=400)),
                ('accuserphone', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('docs', models.FileField(upload_to='')),
                ('evidence_image', models.ImageField(upload_to='')),
                ('fir', models.FileField(upload_to='')),
            ],
        ),
    ]
