# Generated by Django 4.0 on 2021-12-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0006_alter_profile_accuser_alter_profile_accuseraddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accuser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='accuseraddress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='accuserphone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fir',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
    ]
