# Generated by Django 4.0 on 2021-12-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0012_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname1',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname1',
            new_name='lastname',
        ),
    ]
