# Generated by Django 4.0 on 2021-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0013_rename_firstname1_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
