# Generated by Django 4.0 on 2022-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0014_profile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, upload_to='complaintphoto/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence_docs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fir',
            field=models.FileField(blank=True, null=True, upload_to='fir_documents/'),
        ),
    ]
