# Generated by Django 4.0.1 on 2022-01-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0016_complaint_user_alter_profile_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
