# Generated by Django 4.0.1 on 2022-01-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0024_profile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
