# Generated by Django 4.0.1 on 2022-01-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0026_rename_created_by_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_doc', models.FileField(blank=True, upload_to='evidence_doc/')),
                ('evidence_video', models.FileField(blank=True, upload_to='evidence_video/')),
                ('evidence_img', models.ImageField(blank=True, upload_to='evidence_img/')),
                ('evidence_audio', models.FileField(blank=True, upload_to='evdidence_audio/')),
            ],
        ),
    ]
