# Generated by Django 4.0.1 on 2022-01-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0027_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_audio',
            field=models.FileField(blank=True, upload_to='evidence_audio/'),
        ),
    ]
