# Generated by Django 4.0.1 on 2022-01-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0030_remove_evidence_linked_remove_profile_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='evidence_audio',
            field=models.FileField(blank=True, upload_to='evidence_audio/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='evidence_doc',
            field=models.FileField(blank=True, upload_to='evidence_doc/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='evidence_video',
            field=models.FileField(blank=True, upload_to='evidence_video/'),
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
