# Generated by Django 4.0.1 on 2022-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0031_profile_evidence_audio_profile_evidence_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='accuser_name',
            new_name='accuser_firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evidence_audio',
            new_name='evidence_Audio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evidence_doc',
            new_name='evidence_Documents',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evidence_video',
            new_name='evidence_Video',
        ),
        migrations.AddField(
            model_name='profile',
            name='accuser_lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='accuser_pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
