# Generated by Django 4.0.1 on 2022-01-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0032_rename_accuser_name_profile_accuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='evidence_Video',
            field=models.FileField(blank=True, null=True, upload_to='evidence_video/'),
        ),
    ]
