# Generated by Django 4.0.1 on 2022-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0033_alter_profile_evidence_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='evidence_Video',
            field=models.FileField(null=True, upload_to='evidence_video/'),
        ),
    ]
