# Generated by Django 4.0.1 on 2022-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0034_alter_profile_evidence_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accuser_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
