# Generated by Django 4.0.1 on 2022-01-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0036_profile_evidence_audio1_profile_evidence_audio2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='evidence_img1',
            field=models.ImageField(blank=True, upload_to='evidence_img/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='evidence_img2',
            field=models.ImageField(blank=True, upload_to='evidence_img/'),
        ),
    ]
