# Generated by Django 4.0.1 on 2022-01-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0037_profile_evidence_img1_profile_evidence_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Audio2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Documents2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Video2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_img2',
        ),
    ]
