# Generated by Django 4.0.1 on 2022-01-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0038_remove_profile_evidence_audio2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Audio1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Documents1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Video1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_img1',
        ),
    ]
