# Generated by Django 4.0.1 on 2022-01-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0040_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
