# Generated by Django 4.0.1 on 2022-01-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0041_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='agree',
            field=models.BooleanField(null=True),
        ),
    ]
