# Generated by Django 4.0.1 on 2022-01-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0042_complaint_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
