# Generated by Django 4.0.1 on 2022-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0043_complaint_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
