# Generated by Django 4.0.1 on 2022-01-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0046_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
