# Generated by Django 4.0.1 on 2022-01-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0047_contact_submit_feedback_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.TextField(null=True)),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.contact')),
            ],
        ),
    ]
