# Generated by Django 4.0.1 on 2022-01-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0048_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='evidence_Audio',
            field=models.FileField(null=True, upload_to='evidence_audio/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evidence_Documents',
            field=models.FileField(null=True, upload_to='evidence_doc/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evidence_Video',
            field=models.FileField(null=True, upload_to='evidence_video/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evidence_img',
            field=models.ImageField(null=True, upload_to='evidence_img/'),
        ),
    ]
