# Generated by Django 4.0.1 on 2022-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0051_evi'),
    ]

    operations = [
        migrations.AddField(
            model_name='evi',
            name='evide',
            field=models.FileField(null=True, upload_to='evide/'),
        ),
    ]
