# Generated by Django 4.0.1 on 2022-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0052_evi_evide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_img', models.ImageField(blank=True, upload_to='evidence/img')),
                ('evidence_audio', models.FileField(blank=True, upload_to='evidence/audio')),
                ('evidence_video', models.FileField(blank=True, upload_to='evidence/video')),
                ('evidence_doc', models.FileField(blank=True, upload_to='evidence/doc')),
            ],
        ),
        migrations.DeleteModel(
            name='Evi',
        ),
    ]
