# Generated by Django 4.0.1 on 2022-01-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0053_evidences_delete_evi'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidences',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.profile'),
        ),
    ]
