# Generated by Django 4.0.1 on 2022-01-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0056_alter_evidences_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Audio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Documents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_Video',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='evidence_img',
        ),
    ]
