# Generated by Django 4.0.1 on 2022-01-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0057_remove_profile_evidence_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_audio', models.FileField(blank=True, upload_to='evidence/audio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Evidenced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_doc', models.FileField(blank=True, upload_to='evidence/doc')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_img', models.ImageField(blank=True, upload_to='evidence/img')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_video', models.FileField(blank=True, upload_to='evidence/video')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Evidences',
        ),
    ]
